config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :pages
  resources :teams, only: %i[index show]
  resources :coaches, only: %i[index show]
  resources :players, only: %i[index show]

  get 'static/:permalink', to: 'pages#static', as: 'static'
  get 'search_results', to: 'search#results', as: 'search_results'
  root to: 'teams#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coach.rb
# frozen_string_literal: true

class Coach < ApplicationRecord
  belongs_to :team
  validates :name, presence: true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/player.rb
# frozen_string_literal: true

class Player < ApplicationRecord
  belongs_to :team
  validates :name, :game_name, :country, presence: true
end

app/models/team.rb
# frozen_string_literal: true

class Team < ApplicationRecord
  has_many :players
  has_many :coaches
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coaches_controller.rb
# frozen_string_literal: true

class CoachesController < ApplicationController
  def index
    @coaches = Coach.includes(:team).order(:name).page(params[:page])
  end

  def show
    @coach = Coach.includes(:team).find(params[:id])
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  http_basic_authenticate_with name: 'admin', password: 'password'
  before_action :set_page, only: %i[show edit update destroy]

  def static
    @page = Page.find_by(permalink: params[:permalink])

    redirect_to root_path if @page.nil?
  end

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show; end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit; end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def page_params
    params.require(:page).permit(:title, :content, :permalink)
  end
end

app/controllers/players_controller.rb
# frozen_string_literal: true

class PlayersController < ApplicationController
  def index
    @players = Player.includes(:team).order(:name).page(params[:page])
  end

  def show
    @player = Player.includes(:team).find(params[:id])
  end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  def results
    @query = params[:q]
    @teams = Team.where('name LIKE ?', "%#{@query}%")
    @players = Player.where('name LIKE ?', "%#{@query}%")
    @coaches = Coach.where('name LIKE ?', "%#{@query}%")
  end
end

app/controllers/teams_controller.rb
# frozen_string_literal: true

class TeamsController < ApplicationController
  def index
    @teams = Team.order(:name).page(params[:page]).per(10)
  end

  def show
    @team = Team.includes(:players, :coaches).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/coaches/index.html.erb
<h2>All Coaches</h2>
<%= paginate @coaches %>
<ul class="list-group">
  <% @coaches.each do |coach| %>
    <li class="list-group-item"><%= link_to coach.name, coach %> is a Coach of <%= link_to coach.team.name, coach.team %></li>
  <% end %>
</ul>
<%= paginate @coaches %>

app/views/coaches/show.html.erb
<h2><%= @coach.name %></h2>
<p>This coach is one of <%= @coach.team.coaches.size %> coaches for <%= @coach.team.name %></p>
<p><%= link_to 'Home', root_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Esports</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header>
        <h1>Esports Teams</h1>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <ul class="navbar-nav mr-auto">
            <li class="nav-link"><%= link_to "Home", root_path %></li>
            <li class="nav-link"><%= link_to "Players", players_path %></li>
            <li class="nav-link"><%= link_to "Coaches", coaches_path %></li>
            <li class="nav-link"><%= link_to "About", static_path(permalink: 'about-us') %></li>
          </ul>
          <%= form_tag(search_results_path, method: "get") do %>
            <%= label_tag(:q, "Search for:") %>
            <%= text_field_tag(:q) %>
            <%= submit_tag("Search") %>
          <% end %>
        </nav>
      </header>
      <%= yield %>

      <footer>Note: Data is not accurate! These players are Kpop idols not gamers! Rise up!</footer>
    </div>
  </body>

</html>

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :permalink %>
    <%= form.text_field :permalink %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Permalink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.content %></td>
        <td><%= page.permalink %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @page.content %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @page.permalink %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/pages/static.html.erb
<h2><%= @page.title %></h2>

<p><%= @page.content %></p>

app/views/players/index.html.erb
<h2>All Players</h2>
<%= paginate @players %>
<ul class="list-group">
  <% @players.each do |player| %>
    <li class="list-group-item"><%= link_to player.name, player %> is a member of <%= link_to player.team.name, player.team %></li>
  <% end %>
</ul>
<%= paginate @players %>

app/views/players/show.html.erb
<h2><%= @player.name %></h2>
<p>This player is one of <%= @player.team.players.size %> members for <%= @player.team.name%> from <%= @player.country %> and goes by <%= @player.game_name %></p>
<p><%= link_to 'Home', root_path %></p>

app/views/search/results.html.erb
<h2>Your query for "<%= @query %>" resulted in...</h2>

<h2><%= pluralize(@teams.size, 'Team')%></h2>
<ul class="list-group">
  <% @teams.each do |team| %>
    <li class="list-group-item"><%= link_to team.name, team %></li>
  <% end %>
</ul>

<h2><%= pluralize(@players.size, 'Player')%></h2>
<ul class="list-group">
  <% @players.each do |player| %>
    <li class="list-group-item"><%= link_to player.name, player %> is a member of <%= link_to player.team.name, player.team %></li>
  <% end %>
</ul>

<h2><%= pluralize(@coaches.size, 'Coach')%></h2>
<ul class="list-group">
  <% @coaches.each do |coach| %>
    <li class="list-group-item"><%= link_to coach.name, coach %> is a Coach of <%= link_to coach.team.name, coach.team %></li>
  <% end %>
</ul>